<?
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Mon, 11/17/2008 - 11:02am
 * View: taxonomy_term
 *
**/
echo "<div class=\"view-data-node-title\">" . $title . "<span class=\"view-data-node-edit\">" . $edit ."</span></div>\n";
echo "<span class=\"view-data-node-changed\">" . $changed . "</span>\n";
?>